### ISSUE TITLE
Python Unity 실행 화면

### ISSUE THREAD

**Issue by air83** [reinforcement-learning-kr/Unity_ML_Agents#10]
Sokoban이나 Drone 을 실행할때 아래 화면 처럼 유니티 실행화면이 작게 출력이 됩니다. 
크기를 키울 수 있는 방법이 없을까요?

![q](https://user-images.githubusercontent.com/66672034/88888110-a8e96d00-d278-11ea-8288-349884320087.png)
![q2](https://user-images.githubusercontent.com/66672034/88888907-22ce2600-d27a-11ea-8195-8bd969cbc3cf.png)

**Comment by Kyushik** [comment]
안녕하세요! 유니티 환경을 제작하실 때 하이러키뷰에 있는 Academy를 선택하시고 인스펙터뷰에서 Training Configuration 아래 있는 Width와 Height를 변경해주시면 학습때 창 크기를 변경하여 학습을 수행하실 수 있습니다! 
![image](https://user-images.githubusercontent.com/11716370/88889547-43e34680-d27b-11ea-8c61-723148404f11.png)

**Comment by air83** [comment]
해결 됐습니다, 감사합니다! 책이 도움이 정말 많이 되고 있어요!

**Comment by Kyushik** [comment]
책이 도움이 되셨다니 다행입니다!! ㅜㅜㅜ 책 보시면서 문의사항 생기시면 편하게 올려주세요! :)
