### ISSUE TITLE
pip install agents==0.8.1 오류

### ISSUE THREAD

**Issue by woongdam** [reinforcement-learning-kr/Unity_ML_Agents#12]
안녕하세요 이번에 책을 사게 되어 열심히 프로젝트를 따라하려고 하는 초보자 입니다.

오류가 발생해서 문의 드립니다.
ERROR: Cannot uninstall 'pywin32'. It is a distutils installed project and thus we cannot accurately determine which files belong to it which would lead to only a partial uninstall.

다 설치 되는데 저기서 에러메세지가 뜹니다. 어떻게 해결하면 될까요?

**Comment by Kyushik** [comment]
안녕하세요! 답변이 너무 늦었네요 죄송합니다. 
일단 문의주신 내용 관련해서는 저도 경험해본적이 없는 에러라 도움이 될지는 모르겠으나 구글링한 결과 위주로 답변드겠습니다. 
- 해당 오류를 발생시키는 패키지를 업그레이드하고 다시 수행
https://www.programmersought.com/article/2227664625/

- 관련 패키지의 .egg_info를 삭제 후 재설치
https://www.programmersought.com/article/90294887503/

- ignore 옵션을 추가하여 설치 진행
https://my-repo.tistory.com/4

내용에 대한 참고 부탁드리고 추가 문의사항이 있으신 경우 문의 부탁드립니다! :)
