### ISSUE TITLE
Gridworld 질문이요 (질문이 지워졋네요..ㅠ)

### ISSUE THREAD

**Issue by woongdam** [reinforcement-learning-kr/Unity_ML_Agents#14]
네 답변 감사합니다. 

![image](https://user-images.githubusercontent.com/70656679/92706231-4e6f2080-f38f-11ea-9558-339cd065e0c5.png)

현재 쓰리디로 gridworld 환경을 셋팅하고 있는데..

Unity에서 SetActionMask를 사용하여 

var positionX = (int)transform.position.x ;
        var positionY = (int)transform.position.y;
        var positionZ = (int)transform.position.z ;
        var maxPosition = 9;
        var minPosition = 0;

        if (positionX == minPosition)
        {
            SetActionMask(Left);
        }

        if (positionX == maxPosition)
        {
            SetActionMask(Right);
        }

        if (positionY == minPosition)
        {
            SetActionMask(Down);
        }

        if (positionY == maxPosition)
        {
            SetActionMask(Up);
        }

        if (positionZ == maxPosition)
        {
            SetActionMask(Forward);
        }

        if (positionZ == minPosition)
        {
            SetActionMask(Backward);
        }

이런 코드를 통해 Tensorflow에서 액션을 정할때 조건에 충족되면 해당 액션을 피하려고 하고 있습니다.

하지만 저런 조건에 충족하여도 Tensorflow에서는 해당 액션을 취합니다.

이 부분이 해결이 안되서 고생하고 있습니다. 조언 좀 부탁드립니다.

참고로 : 위의 지붕도 있지만 render을 안해놓은거 뿐입니다.

**Comment by Kyushik** [comment]
오.. 3D GridWorld 군요 재미있네요! 우선 Unity와 Tensorflow는 별개의 도구라서 tensorflow는 취하면 안되는 action을 넘겨줄 수 있습니다. 해당 명령이 tensorflow에서 유니티로 넘어와도 그렇게 처리되게 하지 않으려면 유니티상에서 처리를 해줘야합니다. 흠.. 만약 SetActionMask 함수가 제대로 동작하지 않으면 간단한 조건문을 사용해서 해당 문제를 처리하셔도 괜찮을 것 같습니다.

**Comment by woongdam** [comment]
제가 강화학습을 잘몰라서 그러는데 조건문으로 적는다면 어떻게 하면 action을 막을 수 있나요?
감이 안오네요..

**Comment by Kyushik** [comment]
앗 강화학습에서 나오는 행동은 제한을 할 수가 없습니다. 네트워크의 연산 결과로 도출되는 출력이다보니 예를 들면 벽으로 이동하라는 결과가 나올수도 있습니다. 해당 행동을 유니티에서 받았을 때 해당 행동을 무시하도록 조건문으로 작성해주시면 될 것 같습니다. 예를 들어 강화학습의 결과로 도출한 행동이 오른쪽으로 가는 행동인데 오른쪽에 벽이 있으면 유니티 상에서 코딩하실 때 오른쪽에 벽이 있는 경우 현재 상태를 유지하는 것으로 코딩해주시면 될 것 같습니다.

**Comment by woongdam** [comment]
넵! 감사합니다!!

**Comment by Kyushik** [comment]
네! 화이팅입니다! 혹시 또 문의사항 있으시면 언제든 질문해주세요! :)
