### ISSUE TITLE
전이학습 질문 드립니다

### ISSUE THREAD

**Issue by woongdam** [reinforcement-learning-kr/Unity_ML_Agents#15]
안녕하세요 전에 답변 주셔서 잘해결했습나다. 너무 감사합니다.

다름이 아니라 강화학습도 전이 학습 가능할꺼 같은데.  전이학습 하는 방법에 대해 조언좀 주실수 있나요?

**Comment by Kyushik** [comment]
해결이 잘 되셨다니 너무 다행입니다! 
혹시 전이 학습을 어떤 식으로 적용하실 예정인지 조금 더 자세히 이야기해주시면 좋을 것 같습니다! :)

**Comment by woongdam** [comment]
아 전이학습이 아니라, 학습이 중간에 끊어져서... 저장된 모델로 계속 학습을 이어나가고 싶은데. 어떻게 해야되는지.. 잘몰라서 연락드립니다.!

**Comment by Kyushik** [comment]
아? 중간에 학습이 중단되었는데 저장된 모델 파라미터 다시 불러와서 학습을 이어서 진행하고 싶으신건가요? 혹시 프레임워크 어떤것 사용하실까요? tf나 pytorch 중에..?

**Comment by woongdam** [comment]
저는 tf쓰고 있습니다.!!!

**Comment by Kyushik** [comment]
앗.. 그럼 데이터 저장하고 불러오는 내용 저희 책에 포함되어 있는 것으로 알고있습니다 !!

**Comment by woongdam** [comment]
load_model = true하고 Train_mode = true 하면 되는 건가요??

**Comment by Kyushik** [comment]
네넵 그렇게 하면 모델도 불러오고 해당 모델부터 시작하여 학습도 진행합니다 :)

**Comment by woongdam** [comment]
아 넵 감사합니다!!!!
