### ISSUE TITLE
시각적 관측 여러개 사용 및 시각적 관측 + 수치적 관측 복합 사용 질문건

### ISSUE THREAD

**Issue by woongdam** [reinforcement-learning-kr/Unity_ML_Agents#17]
안녕하세요

현재 책을 통해 많은 프로젝트를 진행하고 있는 학생입니다.

다른 것이 아니라 내장 알고리즘 말고 파이썬으로 학습을 진행하려고 하는데.

시각적 관측을 여러개 사용하는 경우에는 어떻게 코드를 작성해야될지 잘몰라서 질문드리고,

또한, 만약 시각적 관측과 수치적 관측을 복합적으로 사용하려면 코드를 어떻게 작성을 해야되나요..

책 덕분에 많은 것을 배우고 있습니다.
너무 좋은 자료 감사합니다.

**Comment by Kyushik** [comment]
안녕하세요! 이 부분은 네트워크 구조나 데이터 관련 처리를 해주셔야 되는 문제로 생각됩니다. 
일반적으로 시각적 관측을 여러개 사용하는 경우 이미지를 channel의 차원으로 쌓아서 사용하는 경우가 많습니다. 
저희 책에서 DQN 알고리즘 설명할 때 이미지 stack하는 내용이랑 비슷하다고 보시면 되는데요! 
예를 들어 한 이미지가 80x80x3인 경우 이것 4개를 channel dimension으로 stack해서 80x80x12로 만들어서 입력으로 사용하는 것입니다. 
혹은 완전히 다른 이미지를 사용하는 경우 CNN 2개를 따로 사용해서 각 입력을 인코딩 하고 그 인코딩 된 정보를 flatten 한 다음 각 vector들을 concatenate해서 사용하실수도 있구요! 
시각적 관측과 수치적 관측을 복합적으로 이용하는 경우에도 이와 비슷합니다. 시각적 관측의 경우 CNN으로 정보를 인코딩하고 수치적 관측의 경우 일반적인 NN을 통해 정보를 인코딩하는데 네트워크 중간에서 CNN을 통해 얻은 벡터와 NN을 통해 얻은 벡터를 concat해서 하나로 합치고 나머지 action을 얻는 NN 연산을 해주면 됩니다.

**Comment by woongdam** [comment]
아 넵 감사합니다!!!!!
