### ISSUE TITLE
Learning speed 문제

### ISSUE THREAD

**Issue by moonsh** [reinforcement-learning-kr/Unity_ML_Agents#6]
안녕하세요. 
현재 ML-Agent version 0.8 을 설치 할 수 없어서 0.12 버전으로 진행하고 있습니다.
그런데 예제 1_DQN.py 을 실행하면 스텝 30000 이후로 급격하게 속도가 느려지네요.

**Comment by Kyushik** [comment]
안녕하세요!! 흠.. 저희가 확인했을 때는 딱히 그런 문제는 없었던 것 같습니다.... 0.12 버전 자체가 가진 문제일수도 있을 것 같습니다! 0.11이나 0.12의 다른 버전들을 사용하셨을 때도 동일한 오류가 발생하는지 확인이 필요할 것 같습니다. 혹시 어떤 이유로 0.8 버전을 설치하실 수 없으신가요?

**Comment by moonsh** [comment]
@Kyushik 아 0.8 버전 설치 가능하네요. 다른 버전도 같은 문제가 있네요. 하지만 다른 스크립트는 문제 없었습니다. 0.8 버전으로 이용하면 되겠네요. 감사합니다.
